#!/usr/bin/env python3
"""Aggregate `amcc --conformance` output into docs/CONFORMANCE.md.

A dev tool. It decides nothing: every verdict in the TSV was produced by
`Ssim.Conformance` on the Lean side, using the shipping reader, the shipping
`supported` list and the shipping `Dmmeta.isCIdent`. This script counts rows
and formats a table.

The TSV columns are
    kind  name  verdict  reason  reftype  reftype-verdict  name-verdict
and the last two are the reason this is worth a script rather than a `sort |
uniq -c`: a field can be blocked by its reftype, by its name, or by both, and
the number that matters -- how many real fields have a reftype AMCC already
handles -- is only visible when the two are separated.
"""
import argparse
import collections
import datetime
import pathlib
import sys


def read(path):
    rows = []
    for line in pathlib.Path(path).read_text().splitlines():
        parts = line.split("\t")
        if len(parts) != 7:
            print(f"malformed row: {line!r}", file=sys.stderr)
            return None
        rows.append(dict(zip(
            ["kind", "name", "verdict", "reason", "reftype", "rtag", "ntag"],
            parts)))
    return rows


def pct(n, d):
    return "0.0%" if d == 0 else f"{100.0 * n / d:.1f}%"


def table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("modelled", help="TSV from the modelled heads")
    ap.add_argument("all_heads", help="TSV from every head in data/dmmeta")
    ap.add_argument("--corpus", default="~/openacr-mine/data/dmmeta")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    rows = read(args.modelled)
    allrows = read(args.all_heads)
    if rows is None or allrows is None:
        return 1

    ctypes = [r for r in rows if r["kind"] == "ctype"]
    fields = [r for r in rows if r["kind"] == "field"]

    # ---- ctypes ----------------------------------------------------------
    c_ok = [r for r in ctypes if r["verdict"] != "rejected"]
    c_bad = collections.Counter(r["reason"] for r in ctypes
                                if r["verdict"] == "rejected")

    # ---- fields, on two axes --------------------------------------------
    f_gen = [r for r in fields if r["verdict"] == "generated"]
    by_rtag = collections.Counter(r["rtag"] for r in fields)
    # reftype supported (a template emits, or it at least lowers)
    supported = [r for r in fields if r["rtag"] in ("generated", "lowered")]
    blocked_by_name = [r for r in supported if r["ntag"] == "rejected"]
    # the reftypes with no representation at all, by how many fields they block
    no_repr = collections.Counter(
        r["reftype"] or "(missing)" for r in fields if r["rtag"] == "rejected")
    # what those supported-but-blocked fields would have been generated by
    would_gen = collections.Counter(
        r["reason"] for r in blocked_by_name)
    n_val = sum(1 for r in fields if r["reftype"] == "Val")

    # ---- heads -----------------------------------------------------------
    other = [r for r in allrows if r["kind"] == "other"]
    heads = collections.Counter(r["name"] for r in other)

    total_all = len(allrows)
    modelled_rows = total_all - len(other)

    gen_share = pct(len(f_gen), len(fields))
    body = f"""# AMCC — conformance against the real `dmmeta` corpus

*Measured against `{args.corpus}`, {len(ctypes)} ctypes and {len(fields)} fields.
Regenerate with `scripts/conformance/run.sh`; every verdict is produced by
`Ssim.Conformance` in Lean, using the shipping reader, the shipping
`supported` list, the shipping `Dmmeta.mangle` and the shipping
`Dmmeta.isCIdent`. The Python under `scripts/conformance/` slices and counts
and decides nothing.*

---

## The headline

**{len(f_gen)} of {len(fields)} fields ({gen_share}) would be generated**, and
{len(c_ok)} of {len(ctypes)} ctypes ({pct(len(c_ok), len(ctypes))}) are
nameable.

The previous measurement said **one**. The difference is entirely
`Dmmeta.mangle`: `dmmeta` names are namespace-qualified, a dot is not a C
identifier character, and until the mapping existed 4518 fields with a
supported reftype were blocked by their *names*. That number is now {len(blocked_by_name)}.

What remains is what the first measurement predicted would be second: the
reftypes. {by_rtag.get("rejected", 0)} fields
({pct(by_rtag.get("rejected", 0), len(fields))}) have a reftype AMCC has no
representation for, and that is now the *only* thing of any size between the
generator and the corpus.

---

## Ctypes

{table(["verdict", "count", "share"],
       [["accepted", len(c_ok), pct(len(c_ok), len(ctypes))]]
       + [[reason, n, pct(n, len(ctypes))] for reason, n in c_bad.most_common()])}

## Fields, by what AMCC can do with the reftype

{table(["reftype verdict", "count", "share", "meaning"],
       [["generated", by_rtag.get("generated", 0),
         pct(by_rtag.get("generated", 0), len(fields)),
         "a template emits operations"],
        ["lowered", by_rtag.get("lowered", 0),
         pct(by_rtag.get("lowered", 0), len(fields)),
         "becomes a struct field; no operations"],
        ["rejected", by_rtag.get("rejected", 0),
         pct(by_rtag.get("rejected", 0), len(fields)),
         "no representation at all"]])}

## Fields, by what actually blocks them

{table(["blocker", "count", "share of all fields"],
       [["nothing — generated", len(f_gen), pct(len(f_gen), len(fields))],
        ["the name only (reftype is supported)", len(blocked_by_name),
         pct(len(blocked_by_name), len(fields))],
        ["the reftype", by_rtag.get("rejected", 0),
         pct(by_rtag.get("rejected", 0), len(fields))]])}

Broken down, the name-only blockers are:

{table(["reason", "fields"],
       [[reason, n] for reason, n in would_gen.most_common()])}

---

## Top reasons for rejection, by how many real fields each blocks

{table(["rank", "reason", "fields blocked"],
       [[i + 1, f"reftype `{name}` has no representation", n]
        for i, (name, n) in enumerate(no_repr.most_common())]
       + ([[len(no_repr) + 1, "the name, after mangling", len(blocked_by_name)]]
          if blocked_by_name else []))}

---

## What the numbers do not capture

The census reads the `dmmeta` record types AMCC models — `dmmeta.ctype`,
`dmmeta.field`, and the attribute tables the join carries (`dmmeta.inlary`,
`dmmeta.smallstr`). `data/dmmeta` has
**{len(heads)} more that AMCC does not model at all**, carrying
{len(other)} records — {pct(len(other), total_all)} of the corpus, against
{pct(modelled_rows, total_all)} for the ones AMCC reads. The largest are:

{table(["record type", "records"],
       [[f"`{h}`", n] for h, n in heads.most_common(10)])}

Three of those matter more than their counts suggest, and none of them is a
field-level verdict this census could produce:

- **`dmmeta.xref` ({heads.get('dmmeta.xref', 0)} records).** Cross-reference
  maintenance is the centre of the library — `docs/GOALS.md` calls it central,
  not peripheral. AMCC models it (`Amcc/Spec/Algebra.lean`) and emits none. A
  field counted "generated" above gets its accessors and *not* its
  participation in the indexes that must be updated when a record is inserted.
  The percentage above therefore overstates what a user would get.
- **Cursors.** Every access pattern in `amc` has one, and they appear in the
  generated API rather than in `data/dmmeta` as their own head, so they are
  invisible to a record census entirely.
- **The ssim layer itself** — `acr`, query mode, `ssimfile` loading,
  `Print`/`ReadStrptrMaybe`, `CopyIn`/`CopyOut`. AMCC reads ssim as a *front
  end* and generates none of the machinery `amc` generates for handling it.

**Every rejection above is now a gap, not a name AMCC never heard of.**
`Dmmeta.Reftype` used to have twenty constructors against `reftype.ssim`'s
thirty-five, so fifteen of the reftypes in this table came back as *unknown* —
which reads as a typo in the corpus rather than as something AMCC does not
model. The vocabulary is complete; the verdicts are unchanged, but they now
mean what they say.

**`Smallstr` is modelled and still counted rejected**, and the distinction is
worth keeping. Its `dmmeta.smallstr` record is read, joined onto the field,
checked (including `amc`'s own 255 ceiling on an `rpascal` length) and printed
back byte-for-byte; `Templates/Smallstr.lean` states all three `strtype`
abstractions and proves `rpascal`'s read-back law. What is missing is
emission: `amc` writes `u8` and the C subset has no eight-bit scalar, so
`Dmmeta.fieldTy` cannot lower the field and `Ssim.supported` does not list the
reftype. `docs/DIVERGENCE.md` §3.8. The census reports what AMCC would
*generate*, so 140 fields stay in the rejected column until that changes —
counting them any other way would be the overstatement this file exists to
prevent.

**The attribute join makes the next few tables cheap, not free.**
`dmmeta.inlary` and `dmmeta.smallstr` go through one registry keyed by
`Dmmeta.AttrTag`, so `bitfld` (75 fields), `charset` (23), `lenfld`, `substr`
and `fconst` (337 records) each need a payload arm and nothing else. That is
the *join*. Each still needs its own lowering and its own law before this
table moves.

**The census does not model the layout at all.** It answers "would AMCC name
and represent this field", and says nothing about whether the *program* built
from the ctype it belongs to passes `CSubset.Wf.check`. Since e08a3e8 the
structure templates emit the whole lowered table, so a ctype whose fields all
count as generated still produces nothing unless a template runs over it —
`Templates.Layout.layoutCheck`, not this census, is where "can be lowered
today" is decided. The headline is an upper bound in that direction too.

**The census is per-record and misses the whole-schema clauses.**
`Dmmeta.check` has three checks that need every ctype and field at once — two
mangled names colliding, two qualified names colliding, and a field named what
a template would generate — and `Ssim.Conformance.classify` decides one tuple
at a time. So the generated count above is an **upper bound** on that axis too.
The last of the three is known to bite in the corpus: `c_next` alongside a
field `c`, and `line_n` alongside `line` (5 of those), are exactly the shape
`clashesGenerated` rejects. Under ten fields, but not zero, and the census
does not currently show them.

Two further caveats on the reading of the table:

- A "generated" verdict is about the reftype and the names, not about the
  whole ctype. A ctype whose fields are individually fine can still fail
  `Dmmeta.check` — for the layout-acyclicity rule, for a duplicate qualified
  name — and the census does not run the whole-schema check, because the
  corpus does not get far enough for it to mean anything.
- `Val` dominates the corpus ({n_val} fields, {pct(n_val, len(fields))} of the
  total), and a `Val` whose `arg` is a ctype AMCC cannot lower —
  `algo.cstring`, `algo_lib.Replscope` — is counted here by its reftype and
  would still fail at lowering. The number is an upper bound.
"""
    pathlib.Path(args.out).write_text(body)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
